//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	CaptchaInvalid       ErrorCode = "CaptchaInvalid"
	IdempotencyConflict  ErrorCode = "IdempotencyConflict"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBallot        ErrorCode = "InvalidBallot"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
	PollNotActive        ErrorCode = "PollNotActive"
	VersionConflict      ErrorCode = "VersionConflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AuthError:
		return true
	case CaptchaInvalid:
		return true
	case IdempotencyConflict:
		return true
	case InputValidationError:
		return true
	case InternalError:
		return true
	case InvalidBallot:
		return true
	case InvalidBody:
		return true
	case InvalidCursor:
		return true
	case LimitOutOfBounds:
		return true
	case NotFound:
		return true
	case PollNotActive:
		return true
	case VersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for PollStatus.
const (
	Active   PollStatus = "Active"
	Closed   PollStatus = "Closed"
	Upcoming PollStatus = "Upcoming"
)

// Valid indicates whether the value is a known member of the PollStatus enum.
func (e PollStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for PublicResultsLevel.
const (
	Full        PublicResultsLevel = "Full"
	None        PublicResultsLevel = "None"
	Percentages PublicResultsLevel = "Percentages"
	Rankings    PublicResultsLevel = "Rankings"
)

// Valid indicates whether the value is a known member of the PublicResultsLevel enum.
func (e PublicResultsLevel) Valid() bool {
	switch e {
	case Full:
		return true
	case None:
		return true
	case Percentages:
		return true
	case Rankings:
		return true
	default:
		return false
	}
}

// Defines values for ResultsVisibility.
const (
	AdminOnly  ResultsVisibility = "AdminOnly"
	AfterClose ResultsVisibility = "AfterClose"
	Live       ResultsVisibility = "Live"
)

// Valid indicates whether the value is a known member of the ResultsVisibility enum.
func (e ResultsVisibility) Valid() bool {
	switch e {
	case AdminOnly:
		return true
	case AfterClose:
		return true
	case Live:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`

	// Message Example: An unexpected error occurred.
	Message string `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// OptionResult defines model for OptionResult.
type OptionResult struct {
	// Count Vote count for this option. Only present when level is Full.
	//
	// Example: 10
	Count *int `json:"count,omitempty"`

	// OptionId Example: 00000000-0000-0000-0000-000000000000
	OptionId openapi_types.UUID `json:"optionId"`

	// Percentage Percentage of votes for this option (0-100). Only present when level is Percentages.
	//
	// Example: 42
	Percentage *int `json:"percentage,omitempty"`

	// Rank Rank of this option (1-based, ties share rank). Only present when level is Rankings.
	//
	// Example: 1
	Rank *int `json:"rank,omitempty"`
}

// Poll defines model for Poll.
type Poll struct {
	// Description Example: Vote for the Most Valuable Player of the Eastern Finals
	Description *string `json:"description,omitempty"`

	// EndTime Example: 2026-08-08T00:00:00.000Z
	EndTime time.Time `json:"endTime"`

	// Groups Optional groups that options belong to, e.g. teams. Options are nested inside their group.
	Groups *[]PollGroup `json:"groups,omitempty"`

	// Id Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Example: Eastern Finals MVP
	Name string `json:"name"`

	// Options Options that don't belong to a group
	Options *[]PollOption `json:"options,omitempty"`

	// PublicResultsLevel Controls what level of results detail non-admin users can see:
	// - Full: option counts and total votes are visible (admins always see this)
	// - Percentages: percentages per option without raw counts or total votes
	// - Rankings: ordered ranking per option without any numbers
	// - None: no results visible to non-admin users
	//
	//
	// Example: Full
	PublicResultsLevel *PublicResultsLevel `json:"publicResultsLevel,omitempty"`

	// ResultsVisibility Controls who can view a poll's results and when:
	// - Live: anyone can view results at any time
	// - AfterClose: anyone can view results after the poll's end time, admins at any time
	// - AdminOnly: only admins can view results
	//
	//
	// Example: AfterClose
	ResultsVisibility ResultsVisibility `json:"resultsVisibility"`

	// StartTime Example: 2026-08-07T19:00:00.000Z
	StartTime time.Time `json:"startTime"`

	// Status Computed status of a poll based on the current time
	//
	// Example: Active
	Status *PollStatus `json:"status,omitempty"`

	// Version Example: 1
	Version *int `json:"version,omitempty"`

	// VoteConfig Limits on how many options a single ballot can select. Defaults to one selection total.
	VoteConfig *VoteConfig `json:"voteConfig,omitempty"`
}

// PollGroup defines model for PollGroup.
type PollGroup struct {
	// Color Example: #70b2e0
	Color *string `json:"color,omitempty"`

	// Id Assigned by the server when omitted. Include on updates to preserve the group's identity.
	//
	// Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ImageUrl Example: https://assets.icaa.world/42e777a4-2757-4bbf-bdaa-79303aafc9ba.png
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name Example: Team Boston
	Name string `json:"name"`

	// Options The options that belong to this group
	Options []PollOption `json:"options"`
}

// PollOption defines model for PollOption.
type PollOption struct {
	// Id Assigned by the server when omitted. Include on updates to preserve the option's identity and its votes.
	//
	// Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ImageUrl Example: https://assets.icaa.world/9ccd9c08-d3cb-4a25-a386-675c9c299c61.jpg
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name Example: Cameron Cardwell
	Name string `json:"name"`

	// Subtitle Extra info about the option, e.g. a player's number
	//
	// Example: #17
	Subtitle *string `json:"subtitle,omitempty"`
}

// PollResults defines model for PollResults.
type PollResults struct {
	// Level Controls what level of results detail non-admin users can see:
	// - Full: option counts and total votes are visible (admins always see this)
	// - Percentages: percentages per option without raw counts or total votes
	// - Rankings: ordered ranking per option without any numbers
	// - None: no results visible to non-admin users
	//
	//
	// Example: Full
	Level PublicResultsLevel `json:"level"`

	// PollId Example: 00000000-0000-0000-0000-000000000000
	PollId  openapi_types.UUID `json:"pollId"`
	Results []OptionResult     `json:"results"`

	// TotalVotes Total amount of ballots cast. Only present when level is Full.
	//
	// Example: 42
	TotalVotes *int `json:"totalVotes,omitempty"`
}

// PollStatus Computed status of a poll based on the current time
//
// Example: Active
type PollStatus string

// PublicResultsLevel Controls what level of results detail non-admin users can see:
// - Full: option counts and total votes are visible (admins always see this)
// - Percentages: percentages per option without raw counts or total votes
// - Rankings: ordered ranking per option without any numbers
// - None: no results visible to non-admin users
//
// Example: Full
type PublicResultsLevel string

// ResultsVisibility Controls who can view a poll's results and when:
// - Live: anyone can view results at any time
// - AfterClose: anyone can view results after the poll's end time, admins at any time
// - AdminOnly: only admins can view results
//
// Example: AfterClose
type ResultsVisibility string

// VoteBallot defines model for VoteBallot.
type VoteBallot struct {
	// OptionIds IDs of the options to vote for
	//
	// Example: ["00000000-0000-0000-0000-000000000000"]
	OptionIds []openapi_types.UUID `json:"optionIds"`
}

// VoteConfig Limits on how many options a single ballot can select. Defaults to one selection total.
type VoteConfig struct {
	// MaxSelections Max amount of options that can be selected in a single ballot
	//
	// Example: 1
	MaxSelections *int `json:"maxSelections,omitempty"`

	// MaxSelectionsPerGroup Max amount of options that can be selected per group in a single ballot. No limit if unset.
	//
	// Example: 1
	MaxSelectionsPerGroup *int `json:"maxSelectionsPerGroup,omitempty"`
}

// VoteConfirmation defines model for VoteConfirmation.
type VoteConfirmation struct {
	// OptionIds The options that were recorded for this ballot
	//
	// Example: ["00000000-0000-0000-0000-000000000000"]
	OptionIds []openapi_types.UUID `json:"optionIds"`

	// PollId Example: 00000000-0000-0000-0000-000000000000
	PollId openapi_types.UUID `json:"pollId"`
}

// GetVotingV1PollsParams defines parameters for GetVotingV1Polls.
type GetVotingV1PollsParams struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of polls to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchVotingV1PollsIdParams defines parameters for PatchVotingV1PollsId.
type PatchVotingV1PollsIdParams struct {
	// Version The version of the poll you last read, used for optimistic locking. The update will only succeed if this matches the current version on the server.
	Version int `form:"version" json:"version"`
}

// PostVotingV1PollsIdVotesParams defines parameters for PostVotingV1PollsIdVotes.
type PostVotingV1PollsIdVotesParams struct {
	// CfTurnstileResponse Cloudflare turnstile CAPTCHA
	CfTurnstileResponse string `json:"cf-turnstile-response"`

	// IdempotencyKey Client generated unique key for this ballot, used to deduplicate retried requests
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// PostVotingV1PollsJSONRequestBody defines body for PostVotingV1Polls for application/json ContentType.
type PostVotingV1PollsJSONRequestBody = Poll

// PatchVotingV1PollsIdJSONRequestBody defines body for PatchVotingV1PollsId for application/json ContentType.
type PatchVotingV1PollsIdJSONRequestBody = Poll

// PostVotingV1PollsIdVotesJSONRequestBody defines body for PostVotingV1PollsIdVotes for application/json ContentType.
type PostVotingV1PollsIdVotesJSONRequestBody = VoteBallot

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetVotingV1Polls Get all polls
	// (GET /voting/v1/polls)
	GetVotingV1Polls(w http.ResponseWriter, r *http.Request, params GetVotingV1PollsParams)
	// PostVotingV1Polls Create a new poll
	// (POST /voting/v1/polls)
	PostVotingV1Polls(w http.ResponseWriter, r *http.Request)
	// DeleteVotingV1PollsId Delete a poll
	// (DELETE /voting/v1/polls/{id})
	DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetVotingV1PollsId Get a poll
	// (GET /voting/v1/polls/{id})
	GetVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PatchVotingV1PollsId Update a poll
	// (PATCH /voting/v1/polls/{id})
	PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PatchVotingV1PollsIdParams)
	// GetVotingV1PollsIdResults Get the results of a poll
	// (GET /voting/v1/polls/{id}/results)
	GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostVotingV1PollsIdVotes Vote on a poll
	// (POST /voting/v1/polls/{id}/votes)
	PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PostVotingV1PollsIdVotesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetVotingV1Polls operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1Polls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVotingV1PollsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1Polls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVotingV1Polls operation middleware
func (siw *ServerInterfaceWrapper) PostVotingV1Polls(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVotingV1Polls(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVotingV1PollsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1PollsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchVotingV1PollsIdParams

	// ------------- Required query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchVotingV1PollsId(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVotingV1PollsIdResults operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1PollsIdResults(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVotingV1PollsIdVotes operation middleware
func (siw *ServerInterfaceWrapper) PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVotingV1PollsIdVotesParams

	headers := r.Header

	// ------------- Required header parameter "cf-turnstile-response" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cf-turnstile-response")]; found {
		var CfTurnstileResponse string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "cf-turnstile-response", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "cf-turnstile-response", valueList[0], &CfTurnstileResponse, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cf-turnstile-response", Err: err})
			return
		}

		params.CfTurnstileResponse = CfTurnstileResponse

	} else {
		err := fmt.Errorf("Header parameter cf-turnstile-response is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "cf-turnstile-response", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVotingV1PollsIdVotes(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls", wrapper.GetVotingV1Polls)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/voting/v1/polls", wrapper.PostVotingV1Polls)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.DeleteVotingV1PollsId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.GetVotingV1PollsId)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.PatchVotingV1PollsId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/voting/v1/polls/{id}/votes", wrapper.PostVotingV1PollsIdVotes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls/{id}/results", wrapper.GetVotingV1PollsIdResults)

	return m
}

type GetVotingV1PollsRequestObject struct {
	Params GetVotingV1PollsParams
}

type GetVotingV1PollsResponseObject interface {
	VisitGetVotingV1PollsResponse(w http.ResponseWriter) error
}

type GetVotingV1Polls200JSONResponse struct {
	// Cursor Example: Y29uZ3JhdHMsIHlvdSBmb3VuZCB0aGUgZWFzdGVyIGVnZw==
	Cursor *string `json:"cursor,omitempty"`
	Data   []Poll  `json:"data"`

	// HasNextPage Example: true
	HasNextPage bool `json:"hasNextPage"`
}

func (response GetVotingV1Polls200JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1Polls400JSONResponse Error

func (response GetVotingV1Polls400JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1Polls500JSONResponse Error

func (response GetVotingV1Polls500JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsRequestObject struct {
	Body *PostVotingV1PollsJSONRequestBody
}

type PostVotingV1PollsResponseObject interface {
	VisitPostVotingV1PollsResponse(w http.ResponseWriter) error
}

type PostVotingV1Polls200JSONResponse Poll

func (response PostVotingV1Polls200JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1Polls400JSONResponse Error

func (response PostVotingV1Polls400JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1Polls500JSONResponse Error

func (response PostVotingV1Polls500JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVotingV1PollsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteVotingV1PollsIdResponseObject interface {
	VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type DeleteVotingV1PollsId204Response struct {
}

func (response DeleteVotingV1PollsId204Response) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVotingV1PollsId404JSONResponse Error

func (response DeleteVotingV1PollsId404JSONResponse) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVotingV1PollsId500JSONResponse Error

func (response DeleteVotingV1PollsId500JSONResponse) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetVotingV1PollsIdResponseObject interface {
	VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type GetVotingV1PollsId200JSONResponse struct {
	Poll Poll `json:"poll"`
}

func (response GetVotingV1PollsId200JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId400JSONResponse Error

func (response GetVotingV1PollsId400JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId404JSONResponse Error

func (response GetVotingV1PollsId404JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId500JSONResponse Error

func (response GetVotingV1PollsId500JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsIdRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params PatchVotingV1PollsIdParams
	Body   *PatchVotingV1PollsIdJSONRequestBody
}

type PatchVotingV1PollsIdResponseObject interface {
	VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type PatchVotingV1PollsId200JSONResponse struct {
	Poll Poll `json:"poll"`
}

func (response PatchVotingV1PollsId200JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId400JSONResponse Error

func (response PatchVotingV1PollsId400JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId404JSONResponse Error

func (response PatchVotingV1PollsId404JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId409JSONResponse Error

func (response PatchVotingV1PollsId409JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId500JSONResponse Error

func (response PatchVotingV1PollsId500JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResultsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetVotingV1PollsIdResultsResponseObject interface {
	VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error
}

type GetVotingV1PollsIdResults200JSONResponse PollResults

func (response GetVotingV1PollsIdResults200JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults403JSONResponse Error

func (response GetVotingV1PollsIdResults403JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults404JSONResponse Error

func (response GetVotingV1PollsIdResults404JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults500JSONResponse Error

func (response GetVotingV1PollsIdResults500JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotesRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params PostVotingV1PollsIdVotesParams
	Body   *PostVotingV1PollsIdVotesJSONRequestBody
}

type PostVotingV1PollsIdVotesResponseObject interface {
	VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error
}

type PostVotingV1PollsIdVotes200JSONResponse VoteConfirmation

func (response PostVotingV1PollsIdVotes200JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes400JSONResponse Error

func (response PostVotingV1PollsIdVotes400JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes403JSONResponse Error

func (response PostVotingV1PollsIdVotes403JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes404JSONResponse Error

func (response PostVotingV1PollsIdVotes404JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes409JSONResponse Error

func (response PostVotingV1PollsIdVotes409JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes500JSONResponse Error

func (response PostVotingV1PollsIdVotes500JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetVotingV1Polls Get all polls
	// (GET /voting/v1/polls)
	GetVotingV1Polls(ctx context.Context, request GetVotingV1PollsRequestObject) (GetVotingV1PollsResponseObject, error)
	// PostVotingV1Polls Create a new poll
	// (POST /voting/v1/polls)
	PostVotingV1Polls(ctx context.Context, request PostVotingV1PollsRequestObject) (PostVotingV1PollsResponseObject, error)
	// DeleteVotingV1PollsId Delete a poll
	// (DELETE /voting/v1/polls/{id})
	DeleteVotingV1PollsId(ctx context.Context, request DeleteVotingV1PollsIdRequestObject) (DeleteVotingV1PollsIdResponseObject, error)
	// GetVotingV1PollsId Get a poll
	// (GET /voting/v1/polls/{id})
	GetVotingV1PollsId(ctx context.Context, request GetVotingV1PollsIdRequestObject) (GetVotingV1PollsIdResponseObject, error)
	// PatchVotingV1PollsId Update a poll
	// (PATCH /voting/v1/polls/{id})
	PatchVotingV1PollsId(ctx context.Context, request PatchVotingV1PollsIdRequestObject) (PatchVotingV1PollsIdResponseObject, error)
	// GetVotingV1PollsIdResults Get the results of a poll
	// (GET /voting/v1/polls/{id}/results)
	GetVotingV1PollsIdResults(ctx context.Context, request GetVotingV1PollsIdResultsRequestObject) (GetVotingV1PollsIdResultsResponseObject, error)
	// PostVotingV1PollsIdVotes Vote on a poll
	// (POST /voting/v1/polls/{id}/votes)
	PostVotingV1PollsIdVotes(ctx context.Context, request PostVotingV1PollsIdVotesRequestObject) (PostVotingV1PollsIdVotesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetVotingV1Polls operation middleware
func (sh *strictHandler) GetVotingV1Polls(w http.ResponseWriter, r *http.Request, params GetVotingV1PollsParams) {
	var request GetVotingV1PollsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1Polls(ctx, request.(GetVotingV1PollsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1Polls")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVotingV1Polls operation middleware
func (sh *strictHandler) PostVotingV1Polls(w http.ResponseWriter, r *http.Request) {
	var request PostVotingV1PollsRequestObject

	var body PostVotingV1PollsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVotingV1Polls(ctx, request.(PostVotingV1PollsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVotingV1Polls")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVotingV1PollsResponseObject); ok {
		if err := validResponse.VisitPostVotingV1PollsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVotingV1PollsId operation middleware
func (sh *strictHandler) DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteVotingV1PollsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVotingV1PollsId(ctx, request.(DeleteVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitDeleteVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVotingV1PollsId operation middleware
func (sh *strictHandler) GetVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetVotingV1PollsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1PollsId(ctx, request.(GetVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchVotingV1PollsId operation middleware
func (sh *strictHandler) PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PatchVotingV1PollsIdParams) {
	var request PatchVotingV1PollsIdRequestObject

	request.Id = id
	request.Params = params

	var body PatchVotingV1PollsIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchVotingV1PollsId(ctx, request.(PatchVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitPatchVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVotingV1PollsIdResults operation middleware
func (sh *strictHandler) GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetVotingV1PollsIdResultsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1PollsIdResults(ctx, request.(GetVotingV1PollsIdResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1PollsIdResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsIdResultsResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsIdResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVotingV1PollsIdVotes operation middleware
func (sh *strictHandler) PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PostVotingV1PollsIdVotesParams) {
	var request PostVotingV1PollsIdVotesRequestObject

	request.Id = id
	request.Params = params

	var body PostVotingV1PollsIdVotesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVotingV1PollsIdVotes(ctx, request.(PostVotingV1PollsIdVotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVotingV1PollsIdVotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVotingV1PollsIdVotesResponseObject); ok {
		if err := validResponse.VisitPostVotingV1PollsIdVotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ft5b9vGtv8qA+YCaQFq8RbHAu4firLUt4ljJI6bJvYrRuSRNPFwhp0ZSlYDA+/TvA/2PsnDOUNSpEjZ",
	"TuokfWmDi1uTnOXMWX5nG30MIp2kWoFyNhh8DGw0g4TTn0+M0Qb/SI1OwTgB9DrSMeB//2VgEgyCe73V",
	"Ar18do+mjnDgVRgkYC2f0hy45EkqIRgEQ8UyBZcpRA5iBjie6SjKjIG4G4SBW6Y4zDoj1DS4ugoDA79n",
	"wkAcDN57GlYrn5fj9fgDRA53XZGA+6oswXmHyoFRXPqjhcFzkQj3MnMvJ490pmIbhMGhmnMp4lFmLA05",
	"0u4pflt9eqTjJT2lmTvFF9wJrYolh5mbFX+PeOqiGc/nBWFwrKU80m4YOTGHyopcSu3wOYYk1Q5UtBxp",
	"NZEiwrenYKzQqnxz3mBPGLxMkYhXYDPp2mSWKXodg42MoLHBIDjVDhh9YxNtmJsJyzR97LKXSi5ZasCC",
	"cmwxA8UkzEEyYdnTTEqUUSnNrX5JkVAOpmCQJL/SYVwXfD//12n5v+JfEAYTbRLugkGQZcS5xoFTMBEo",
	"lytW/VzH5TemJ2yuHdj1A7If+p2tfv/Haw+6WsfWzru73XZew9VFk5ZXXF0gFbW9tzpjbiEOGQqI2Rk3",
	"wHD69eTgUkJN67RsNUlZM5ZSDm1mghrZ1JfaEarSI43xrAT2QlvHTrnM+FgCO5Z8CcYfFdgTbtHU2FOh",
	"uES7Svjlc1BTN0N16fdbJAoqPhHJGk5s97cfdPoPO/2HJ/3+gP7X7ff776oqEnMHHYdTW1adGp2lzUPl",
	"BsMl8wOYm3GXy8eyMUitpszpkEF32mUOeGK77GX+GcWlwCJyCWVFDHhkYfxSKB3hILE3gSSy/hnOQDJz",
	"urkxfInP4m7MxgCPUaOCgTMZtLBH8XWO1yXHXpwe16W3vbcXBolQxfNOy6o5HzdxPed2rNV9t+I1456B",
	"n8I/v14bA9NsLEXkAdE+RxO6cb3mDLIkej4VVoyFFG550zKvGhOuwsA6btw12r1/snXwOdptHXfZrTj1",
	"2o+8CoO5dyc1SrY2qkoF4BBI0QmJ6U0bnq5GrqMRqWVBQq5/Vf6scKCN9+WJN2GZN6gWByh9LLPi/b39",
	"/ngb0GhS7lDjg0HwX/fe9zsHvDMZdp6ef3xw9a82nnvTrOv10FoxVRCz8ZLgz4KZg/H4rRPhHMRddqgi",
	"mcXAtGJZimK1qPWE9WZOGOIN4L5lIgblhFvWoP7OfKdI+BTeGFlnyMy51A56PW4tONsVEefdhTYy7u1u",
	"w/7+Pt/tbO/v7Xd2x+NJZxxz3tk/2OnvcD6JDsa8m6ppHSj2WlG+CTgnwBP2SFtHClH3EzWk2foUpDmZ",
	"QQnnhDYrnCFXfGdQs6bfuUIXdG3S05elc60r6pdULk9TRbsYVzETzvoQ6a+hawdRFB9E/YedeCcad3b5",
	"9l6H7zx80HmwvxcdRNsHB9GDre6H9DN1bcQTMFqxETfxAqT8dIWz2dgJJ1uizieXznAm1EQzPtaZq/A8",
	"DyM4SylIum+ZypIxmBrH723tt5BzfSJEJ9ykY7knaiqZ/Hx3mGopv1RIb1b03soqazlPSwjgtOMSXVEb",
	"POA3xhNKfvSEjSkFsyzi1n1a8tOWDKxJKWdamDN+ddJNkntduvU61SOdpBmGnd4LIuGc4eqM8gk0flQ6",
	"SqOVY65wqD77fZNGOhEE02UGOpLaAqUGldy8+Hhj9HjcGmSt06yc0dKyBaKw56OesJwFLAbHhWRKqw6P",
	"E6FYZsGgHBSzAIMz1SGWD4rcidJVS8hF8s3TOwzJ5xgnSGA/0EKWcbngS4vLEOT/iGtVUroBW+WQFv8u",
	"tlgIN0P7NXxRbIcZz2o3XKhIxgZMmxgMxJTACTVtW4mrZW7xNPdIKxgwpUsmFJQ7vc6IM1URIDIiCCvp",
	"LSZWBSFUq1BQF2U+oyG4V21R7Ua5aRLHXMAiV7f7tiQdBYEWQpJ6LuYwwNNqBas55VDPCNRKHDycODCk",
	"f9dMwTGk0/m2gHIXCYSsEPLaovgWdXbANBpxPmp94Rpbn3ttX9GDD8U6a6ZRHdPgKmJNXstpYG6RhbdY",
	"9eFjW6TNZcSiSdMw1a5izfvbYe15Jay5EXUTfnnoBxfur3hcQ9QwyJT4PYP8M0LCplJDO7Kd1vKHOg+o",
	"EmcRwGZ6wRIUacELzqxQUwk5RufQICFyXfYYJpwUxWmGCuTfo+mRuSJQ18WQ8MvXxZhcFLQCHbdO0gt+",
	"WXEQtVgSSRgXu1EVYJ3KtRJNIpRIUNu22hKrGlHHYMok5rMJQgyiCLeFtC470kwiv5mYsExZcN1PIPfq",
	"OsmirrXGtdeofyNSX4ABZiBCYI1XhbsmY7+EOTTqCF8s4NkUJFxnRBiAQpQZ4ZavMQrKk4aI80fADZhh",
	"hoHjx2BMT08LAv7zy0mwrt6Ho+GQ8SgCi9ZzAQpVBedrI/4gKbIZ8JiCVIq4kA6/7uosGMdTlB9xPtL6",
	"QkBBwU2bRTQaEzD8Xj75kJ3G/zYcjZ68fv3bycufnxyttuSp+Bkw78Jt1US35EuKDY8PSXEiA9yRU9ZS",
	"emc11/TCh0pJyGwWzRinQlelVJxwF818TpSH+/4Mp3728PiwUsYYBFvdfrfv81FQPBXBINihV1RdmJGU",
	"en7n3nyrR9Tguym0lOVfgTMC5hjVMCksWTuX0p8hZFYb55NBqpqQ62O4AqjYR3doeLwovgfPwHmqT7eO",
	"aV+kyfAEHBgbDN43HD+1PnDTxQwt0el8o4nRSSGw3zMwy5W8oqJd4mPzurn8un2Qvdv5zyz+6YU9/EnO",
	"49ePkvHOafZu9KjPn72Zvvvl6R/xs9Pl4bNT9W7x73+3mcr1WOil6zSbgItmG2gkyKuRuML+/lo3I+GX",
	"HgD3+jeg4TlF86lW1tvidr/vC07Kge+58DSVIiJ59D5YD44rGtbqVJ6Pd8y+MIi547fOq6gn0AKFM26P",
	"4NIdrzfzasnBWGsJXDXgjSior9ECb1frKDUsLYBk3EU6dj+RxTd2Kts2fsRjhvSDdbTp3tfY9I26UHqh",
	"igoPtUW7NdQPBu/Pw8BmScLN0hv3Chu8v7ItkELhLAbPqRaYGGqPjMA4U7Cg2V2GcWjR28E3Yd4bCQk3",
	"daX5wVsrUt0G9Bxr28CenKnURb0rhnqNbfIT3+Nhx5CfNw6qWkkh7J+0388hCyOenB7P+n+0+v3HRgzx",
	"PqDkLThH9F8PcVYfa+YwWtdq2mbd8/Y+ivjKG4kE11LKe0zvi9pKUSUtktLxkom4oet+Tk3bKZy71tce",
	"Pi4yPyI2d1wYMqz8lmgqbbufvaOwtOnRdtuDdmLOglvm2Rh7Ld798gpFZq20YxOdqfi7VOSaBlIfuy1S",
	"RPTHtNeXAFvVcj36+1508s9EWWl+6eEW2N3M0W4VthTm8c2A/R87bIZJpURSTO6a1vSG+mZlRR3Nqcue",
	"+esh1QjoAiDNb3xgyMQjo60tu27ULnAzWFKkJHxbjkpEaFK5jJjV1GrIM07r+JJx54wYZ9TNO4JFHnz1",
	"il2LWjJtWY3B8MVNcRge+DuAgbDNDeVZeJVattQZk8hfAzwOWWbzQhIyMxHWiYhJHV0INe0yXMMLjy2E",
	"lL5ubLMoAhRbfnMrrwfU2ivlxmqN+W3Z5+rKwy34tTHR/Cahs2fO3YfO3wKU87P8PcF5t3/wlfbFqDDR",
	"sZgInyRypd0MTMGFkBlwZkmYRrYjETpLi/ouI7qad9mclvQqXfBNMZ+HIWoQFTkJgluRrvibB3lj1Tdc",
	"Y0T5RFRS9ryfZsE5ulN6ps7U0BdoY0hBxbbAtbWG37zsGf5/a/mdqaO1LrMFqJLaYJtNISp1uEJS83Lh",
	"bRvVn9+Dvr7p/MNWyLZDtvO///0/P95J2/lMDWtddAMRiDnQGYsFutRGvSnfKK6h/A3Tjpt8WcGaDc6q",
	"kFOVLwTjO18eGV8VZmGAvAifcyHponfZkKuUrv5J+hsuot034NurRmri6sK+0UfMi0tN7dXeEbcouaJh",
	"ridUJNCGJdqseq1a5Rv5EDiHtrn/TYiaiKlvEtuyI3+miqkJX673vz3GIdqVvWfyKafl9RwPzlEEKbWv",
	"wC0Aah7Gd5lwiQLyvVtC6iq/jOn8DMu8NclSox1EeNgpF8o6XJ9uN3LJYp2huhJ6IkROjE5YJAWG7oZa",
	"bHZwpji7gCUdiOgDlPE4n0U3qiLosleQWVzCD6aohbNYTCZAiUDOZ4Eo+YE40oaMjWL4Yewvp30PidhI",
	"6iyeSJSzy4yyTkhgo+HxyeinYUFy2U4umoaTTjm2U+DsLc/x9u3bt93Hb168+LVL/eEuvrgdoaQAU1Ao",
	"G4iZv9RCgl27apDnjU6zGOLMAwvkqlMG9HbT6dY09hs4rrtPFisXnFrTnBJuWq8xfb3GS+M+ygYHS8Rh",
	"rlLcNumyobQYIKFigr/ZtgLSMl2xPGlCEq7DpQEeL1frfYscM2TC/66QRf4HiCFif/EuvwT01QKJslMg",
	"LLnvvHpCvsCJOXz/GXGb/6oqC6HMBqfyVy6q0o8ByyjCr/l5MREuS9u2+b9jo+PMX+rzg4IwyIys/oog",
	"FdWfEARN1H+uI4wIYN62xKDXk/h9pq0b7PT7/V5wdX71fwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
