//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	CaptchaInvalid       ErrorCode = "CaptchaInvalid"
	IdempotencyConflict  ErrorCode = "IdempotencyConflict"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBallot        ErrorCode = "InvalidBallot"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
	PollNotActive        ErrorCode = "PollNotActive"
	VersionConflict      ErrorCode = "VersionConflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AuthError:
		return true
	case CaptchaInvalid:
		return true
	case IdempotencyConflict:
		return true
	case InputValidationError:
		return true
	case InternalError:
		return true
	case InvalidBallot:
		return true
	case InvalidBody:
		return true
	case InvalidCursor:
		return true
	case LimitOutOfBounds:
		return true
	case NotFound:
		return true
	case PollNotActive:
		return true
	case VersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for PollStatus.
const (
	Active   PollStatus = "Active"
	Closed   PollStatus = "Closed"
	Upcoming PollStatus = "Upcoming"
)

// Valid indicates whether the value is a known member of the PollStatus enum.
func (e PollStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for PublicResultsLevel.
const (
	Full        PublicResultsLevel = "Full"
	None        PublicResultsLevel = "None"
	Percentages PublicResultsLevel = "Percentages"
	Rankings    PublicResultsLevel = "Rankings"
)

// Valid indicates whether the value is a known member of the PublicResultsLevel enum.
func (e PublicResultsLevel) Valid() bool {
	switch e {
	case Full:
		return true
	case None:
		return true
	case Percentages:
		return true
	case Rankings:
		return true
	default:
		return false
	}
}

// Defines values for ResultsVisibility.
const (
	AdminOnly  ResultsVisibility = "AdminOnly"
	AfterClose ResultsVisibility = "AfterClose"
	Live       ResultsVisibility = "Live"
)

// Valid indicates whether the value is a known member of the ResultsVisibility enum.
func (e ResultsVisibility) Valid() bool {
	switch e {
	case AdminOnly:
		return true
	case AfterClose:
		return true
	case Live:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`

	// Message Example: An unexpected error occurred.
	Message string `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// OptionResult defines model for OptionResult.
type OptionResult struct {
	// Count Vote count for this option. Only present when level is Full.
	//
	// Example: 10
	Count *int `json:"count,omitempty"`

	// OptionId Example: 00000000-0000-0000-0000-000000000000
	OptionId openapi_types.UUID `json:"optionId"`

	// Percentage Percentage of votes for this option (0-100). Only present when level is Percentages.
	//
	// Example: 42
	Percentage *int `json:"percentage,omitempty"`

	// Rank Rank of this option (1-based, ties share rank). Only present when level is Rankings.
	//
	// Example: 1
	Rank *int `json:"rank,omitempty"`
}

// Poll defines model for Poll.
type Poll struct {
	// Description Example: Vote for the Most Valuable Player of the Eastern Finals
	Description *string `json:"description,omitempty"`

	// EndTime Example: 2026-08-08T00:00:00.000Z
	EndTime time.Time `json:"endTime"`

	// Groups Optional groups that options belong to, e.g. teams. Options are nested inside their group.
	Groups *[]PollGroup `json:"groups,omitempty"`

	// Id Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Example: Eastern Finals MVP
	Name string `json:"name"`

	// Options Options that don't belong to a group
	Options *[]PollOption `json:"options,omitempty"`

	// PublicResultsLevel Controls what level of results detail non-admin users can see:
	// - Full: option counts and total votes are visible (admins always see this)
	// - Percentages: percentages per option without raw counts or total votes
	// - Rankings: ordered ranking per option without any numbers
	// - None: no results visible to non-admin users
	//
	//
	// Example: Full
	PublicResultsLevel *PublicResultsLevel `json:"publicResultsLevel,omitempty"`

	// ResultsVisibility Controls who can view a poll's results and when:
	// - Live: anyone can view results at any time
	// - AfterClose: anyone can view results after the poll's end time, admins at any time
	// - AdminOnly: only admins can view results
	//
	//
	// Example: AfterClose
	ResultsVisibility ResultsVisibility `json:"resultsVisibility"`

	// StartTime Example: 2026-08-07T19:00:00.000Z
	StartTime time.Time `json:"startTime"`

	// Status Computed status of a poll based on the current time
	//
	// Example: Active
	Status *PollStatus `json:"status,omitempty"`

	// Version Example: 1
	Version *int `json:"version,omitempty"`

	// VoteConfig Limits on how many options a single ballot can select. Defaults to one selection total.
	VoteConfig *VoteConfig `json:"voteConfig,omitempty"`
}

// PollGroup defines model for PollGroup.
type PollGroup struct {
	// Color Example: #70b2e0
	Color *string `json:"color,omitempty"`

	// Id Assigned by the server when omitted. Include on updates to preserve the group's identity.
	//
	// Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ImageUrl Example: https://assets.icaa.world/42e777a4-2757-4bbf-bdaa-79303aafc9ba.png
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name Example: Team Boston
	Name string `json:"name"`

	// Options The options that belong to this group
	Options []PollOption `json:"options"`
}

// PollOption defines model for PollOption.
type PollOption struct {
	// Id Assigned by the server when omitted. Include on updates to preserve the option's identity and its votes.
	//
	// Example: 00000000-0000-0000-0000-000000000000
	Id *openapi_types.UUID `json:"id,omitempty"`

	// ImageUrl Example: https://assets.icaa.world/9ccd9c08-d3cb-4a25-a386-675c9c299c61.jpg
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name Example: Cameron Cardwell
	Name string `json:"name"`

	// Subtitle Extra info about the option, e.g. a player's number
	//
	// Example: #17
	Subtitle *string `json:"subtitle,omitempty"`
}

// PollResults defines model for PollResults.
type PollResults struct {
	// Level Controls what level of results detail non-admin users can see:
	// - Full: option counts and total votes are visible (admins always see this)
	// - Percentages: percentages per option without raw counts or total votes
	// - Rankings: ordered ranking per option without any numbers
	// - None: no results visible to non-admin users
	//
	//
	// Example: Full
	Level PublicResultsLevel `json:"level"`

	// PollId Example: 00000000-0000-0000-0000-000000000000
	PollId  openapi_types.UUID `json:"pollId"`
	Results []OptionResult     `json:"results"`

	// TotalVotes Total amount of ballots cast. Only present when level is Full.
	//
	// Example: 42
	TotalVotes *int `json:"totalVotes,omitempty"`
}

// PollStatus Computed status of a poll based on the current time
//
// Example: Active
type PollStatus string

// PublicResultsLevel Controls what level of results detail non-admin users can see:
// - Full: option counts and total votes are visible (admins always see this)
// - Percentages: percentages per option without raw counts or total votes
// - Rankings: ordered ranking per option without any numbers
// - None: no results visible to non-admin users
//
// Example: Full
type PublicResultsLevel string

// ResultsVisibility Controls who can view a poll's results and when:
// - Live: anyone can view results at any time
// - AfterClose: anyone can view results after the poll's end time, admins at any time
// - AdminOnly: only admins can view results
//
// Example: AfterClose
type ResultsVisibility string

// VoteBallot defines model for VoteBallot.
type VoteBallot struct {
	// OptionIds IDs of the options to vote for
	//
	// Example: ["00000000-0000-0000-0000-000000000000"]
	OptionIds []openapi_types.UUID `json:"optionIds"`
}

// VoteConfig Limits on how many options a single ballot can select. Defaults to one selection total.
type VoteConfig struct {
	// MaxSelections Max amount of options that can be selected in a single ballot
	//
	// Example: 1
	MaxSelections *int `json:"maxSelections,omitempty"`

	// MaxSelectionsPerGroup Max amount of options that can be selected per group in a single ballot. No limit if unset.
	//
	// Example: 1
	MaxSelectionsPerGroup *int `json:"maxSelectionsPerGroup,omitempty"`
}

// VoteConfirmation defines model for VoteConfirmation.
type VoteConfirmation struct {
	// OptionIds The options that were recorded for this ballot
	//
	// Example: ["00000000-0000-0000-0000-000000000000"]
	OptionIds []openapi_types.UUID `json:"optionIds"`

	// PollId Example: 00000000-0000-0000-0000-000000000000
	PollId openapi_types.UUID `json:"pollId"`
}

// GetVotingV1PollsParams defines parameters for GetVotingV1Polls.
type GetVotingV1PollsParams struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of polls to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostVotingV1PollsIdVotesParams defines parameters for PostVotingV1PollsIdVotes.
type PostVotingV1PollsIdVotesParams struct {
	// CfTurnstileResponse Cloudflare turnstile CAPTCHA
	CfTurnstileResponse string `json:"cf-turnstile-response"`

	// IdempotencyKey Client generated unique key for this ballot, used to deduplicate retried requests
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// PostVotingV1PollsJSONRequestBody defines body for PostVotingV1Polls for application/json ContentType.
type PostVotingV1PollsJSONRequestBody = Poll

// PatchVotingV1PollsIdJSONRequestBody defines body for PatchVotingV1PollsId for application/json ContentType.
type PatchVotingV1PollsIdJSONRequestBody = Poll

// PostVotingV1PollsIdVotesJSONRequestBody defines body for PostVotingV1PollsIdVotes for application/json ContentType.
type PostVotingV1PollsIdVotesJSONRequestBody = VoteBallot

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetVotingV1Polls Get all polls
	// (GET /voting/v1/polls)
	GetVotingV1Polls(w http.ResponseWriter, r *http.Request, params GetVotingV1PollsParams)
	// PostVotingV1Polls Create a new poll
	// (POST /voting/v1/polls)
	PostVotingV1Polls(w http.ResponseWriter, r *http.Request)
	// DeleteVotingV1PollsId Delete a poll
	// (DELETE /voting/v1/polls/{id})
	DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetVotingV1PollsId Get a poll
	// (GET /voting/v1/polls/{id})
	GetVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PatchVotingV1PollsId Update a poll
	// (PATCH /voting/v1/polls/{id})
	PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetVotingV1PollsIdResults Get the results of a poll
	// (GET /voting/v1/polls/{id}/results)
	GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// PostVotingV1PollsIdVotes Vote on a poll
	// (POST /voting/v1/polls/{id}/votes)
	PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PostVotingV1PollsIdVotesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetVotingV1Polls operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1Polls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVotingV1PollsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1Polls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVotingV1Polls operation middleware
func (siw *ServerInterfaceWrapper) PostVotingV1Polls(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVotingV1Polls(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVotingV1PollsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1PollsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchVotingV1PollsId operation middleware
func (siw *ServerInterfaceWrapper) PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchVotingV1PollsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVotingV1PollsIdResults operation middleware
func (siw *ServerInterfaceWrapper) GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVotingV1PollsIdResults(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVotingV1PollsIdVotes operation middleware
func (siw *ServerInterfaceWrapper) PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVotingV1PollsIdVotesParams

	headers := r.Header

	// ------------- Required header parameter "cf-turnstile-response" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cf-turnstile-response")]; found {
		var CfTurnstileResponse string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "cf-turnstile-response", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "cf-turnstile-response", valueList[0], &CfTurnstileResponse, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cf-turnstile-response", Err: err})
			return
		}

		params.CfTurnstileResponse = CfTurnstileResponse

	} else {
		err := fmt.Errorf("Header parameter cf-turnstile-response is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "cf-turnstile-response", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVotingV1PollsIdVotes(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls", wrapper.GetVotingV1Polls)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/voting/v1/polls", wrapper.PostVotingV1Polls)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.DeleteVotingV1PollsId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.GetVotingV1PollsId)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/voting/v1/polls/{id}", wrapper.PatchVotingV1PollsId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/voting/v1/polls/{id}/votes", wrapper.PostVotingV1PollsIdVotes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/voting/v1/polls/{id}/results", wrapper.GetVotingV1PollsIdResults)

	return m
}

type GetVotingV1PollsRequestObject struct {
	Params GetVotingV1PollsParams
}

type GetVotingV1PollsResponseObject interface {
	VisitGetVotingV1PollsResponse(w http.ResponseWriter) error
}

type GetVotingV1Polls200JSONResponse struct {
	// Cursor Example: Y29uZ3JhdHMsIHlvdSBmb3VuZCB0aGUgZWFzdGVyIGVnZw==
	Cursor *string `json:"cursor,omitempty"`
	Data   []Poll  `json:"data"`

	// HasNextPage Example: true
	HasNextPage bool `json:"hasNextPage"`
}

func (response GetVotingV1Polls200JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1Polls400JSONResponse Error

func (response GetVotingV1Polls400JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1Polls500JSONResponse Error

func (response GetVotingV1Polls500JSONResponse) VisitGetVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsRequestObject struct {
	Body *PostVotingV1PollsJSONRequestBody
}

type PostVotingV1PollsResponseObject interface {
	VisitPostVotingV1PollsResponse(w http.ResponseWriter) error
}

type PostVotingV1Polls200JSONResponse Poll

func (response PostVotingV1Polls200JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1Polls400JSONResponse Error

func (response PostVotingV1Polls400JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1Polls500JSONResponse Error

func (response PostVotingV1Polls500JSONResponse) VisitPostVotingV1PollsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVotingV1PollsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteVotingV1PollsIdResponseObject interface {
	VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type DeleteVotingV1PollsId204Response struct {
}

func (response DeleteVotingV1PollsId204Response) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVotingV1PollsId404JSONResponse Error

func (response DeleteVotingV1PollsId404JSONResponse) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVotingV1PollsId500JSONResponse Error

func (response DeleteVotingV1PollsId500JSONResponse) VisitDeleteVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetVotingV1PollsIdResponseObject interface {
	VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type GetVotingV1PollsId200JSONResponse struct {
	Poll Poll `json:"poll"`
}

func (response GetVotingV1PollsId200JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId400JSONResponse Error

func (response GetVotingV1PollsId400JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId404JSONResponse Error

func (response GetVotingV1PollsId404JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsId500JSONResponse Error

func (response GetVotingV1PollsId500JSONResponse) VisitGetVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsIdRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchVotingV1PollsIdJSONRequestBody
}

type PatchVotingV1PollsIdResponseObject interface {
	VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error
}

type PatchVotingV1PollsId200JSONResponse struct {
	Poll Poll `json:"poll"`
}

func (response PatchVotingV1PollsId200JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId400JSONResponse Error

func (response PatchVotingV1PollsId400JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId404JSONResponse Error

func (response PatchVotingV1PollsId404JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId409JSONResponse Error

func (response PatchVotingV1PollsId409JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PatchVotingV1PollsId500JSONResponse Error

func (response PatchVotingV1PollsId500JSONResponse) VisitPatchVotingV1PollsIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResultsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetVotingV1PollsIdResultsResponseObject interface {
	VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error
}

type GetVotingV1PollsIdResults200JSONResponse PollResults

func (response GetVotingV1PollsIdResults200JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults403JSONResponse Error

func (response GetVotingV1PollsIdResults403JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults404JSONResponse Error

func (response GetVotingV1PollsIdResults404JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVotingV1PollsIdResults500JSONResponse Error

func (response GetVotingV1PollsIdResults500JSONResponse) VisitGetVotingV1PollsIdResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotesRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params PostVotingV1PollsIdVotesParams
	Body   *PostVotingV1PollsIdVotesJSONRequestBody
}

type PostVotingV1PollsIdVotesResponseObject interface {
	VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error
}

type PostVotingV1PollsIdVotes200JSONResponse VoteConfirmation

func (response PostVotingV1PollsIdVotes200JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes400JSONResponse Error

func (response PostVotingV1PollsIdVotes400JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes403JSONResponse Error

func (response PostVotingV1PollsIdVotes403JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes404JSONResponse Error

func (response PostVotingV1PollsIdVotes404JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes409JSONResponse Error

func (response PostVotingV1PollsIdVotes409JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostVotingV1PollsIdVotes500JSONResponse Error

func (response PostVotingV1PollsIdVotes500JSONResponse) VisitPostVotingV1PollsIdVotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetVotingV1Polls Get all polls
	// (GET /voting/v1/polls)
	GetVotingV1Polls(ctx context.Context, request GetVotingV1PollsRequestObject) (GetVotingV1PollsResponseObject, error)
	// PostVotingV1Polls Create a new poll
	// (POST /voting/v1/polls)
	PostVotingV1Polls(ctx context.Context, request PostVotingV1PollsRequestObject) (PostVotingV1PollsResponseObject, error)
	// DeleteVotingV1PollsId Delete a poll
	// (DELETE /voting/v1/polls/{id})
	DeleteVotingV1PollsId(ctx context.Context, request DeleteVotingV1PollsIdRequestObject) (DeleteVotingV1PollsIdResponseObject, error)
	// GetVotingV1PollsId Get a poll
	// (GET /voting/v1/polls/{id})
	GetVotingV1PollsId(ctx context.Context, request GetVotingV1PollsIdRequestObject) (GetVotingV1PollsIdResponseObject, error)
	// PatchVotingV1PollsId Update a poll
	// (PATCH /voting/v1/polls/{id})
	PatchVotingV1PollsId(ctx context.Context, request PatchVotingV1PollsIdRequestObject) (PatchVotingV1PollsIdResponseObject, error)
	// GetVotingV1PollsIdResults Get the results of a poll
	// (GET /voting/v1/polls/{id}/results)
	GetVotingV1PollsIdResults(ctx context.Context, request GetVotingV1PollsIdResultsRequestObject) (GetVotingV1PollsIdResultsResponseObject, error)
	// PostVotingV1PollsIdVotes Vote on a poll
	// (POST /voting/v1/polls/{id}/votes)
	PostVotingV1PollsIdVotes(ctx context.Context, request PostVotingV1PollsIdVotesRequestObject) (PostVotingV1PollsIdVotesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetVotingV1Polls operation middleware
func (sh *strictHandler) GetVotingV1Polls(w http.ResponseWriter, r *http.Request, params GetVotingV1PollsParams) {
	var request GetVotingV1PollsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1Polls(ctx, request.(GetVotingV1PollsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1Polls")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVotingV1Polls operation middleware
func (sh *strictHandler) PostVotingV1Polls(w http.ResponseWriter, r *http.Request) {
	var request PostVotingV1PollsRequestObject

	var body PostVotingV1PollsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVotingV1Polls(ctx, request.(PostVotingV1PollsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVotingV1Polls")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVotingV1PollsResponseObject); ok {
		if err := validResponse.VisitPostVotingV1PollsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVotingV1PollsId operation middleware
func (sh *strictHandler) DeleteVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteVotingV1PollsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVotingV1PollsId(ctx, request.(DeleteVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitDeleteVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVotingV1PollsId operation middleware
func (sh *strictHandler) GetVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetVotingV1PollsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1PollsId(ctx, request.(GetVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchVotingV1PollsId operation middleware
func (sh *strictHandler) PatchVotingV1PollsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchVotingV1PollsIdRequestObject

	request.Id = id

	var body PatchVotingV1PollsIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchVotingV1PollsId(ctx, request.(PatchVotingV1PollsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchVotingV1PollsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchVotingV1PollsIdResponseObject); ok {
		if err := validResponse.VisitPatchVotingV1PollsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVotingV1PollsIdResults operation middleware
func (sh *strictHandler) GetVotingV1PollsIdResults(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetVotingV1PollsIdResultsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVotingV1PollsIdResults(ctx, request.(GetVotingV1PollsIdResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVotingV1PollsIdResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVotingV1PollsIdResultsResponseObject); ok {
		if err := validResponse.VisitGetVotingV1PollsIdResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVotingV1PollsIdVotes operation middleware
func (sh *strictHandler) PostVotingV1PollsIdVotes(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params PostVotingV1PollsIdVotesParams) {
	var request PostVotingV1PollsIdVotesRequestObject

	request.Id = id
	request.Params = params

	var body PostVotingV1PollsIdVotesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVotingV1PollsIdVotes(ctx, request.(PostVotingV1PollsIdVotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVotingV1PollsIdVotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVotingV1PollsIdVotesResponseObject); ok {
		if err := validResponse.VisitPostVotingV1PollsIdVotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fv7cts2s38VDPPNpJ3Rhb7FsWb6h6Jc6jZxPInjpol9OhC5kpCAAAuAktWMZ87TnAc7T/LNLkiKFCnb",
	"SZ2kTZv55qtFgcBiL7/9LRb6EEQ6SbUC5Www+BDYaAYJpz8fGaMN/pEanYJxAuhxpGPA//7HwCQYBHf6",
	"qwn6+dt9enWEAy87QQLW8im9Axc8SSUEg2CoWKbgIoXIQcwAxzMdRZkxEPeCTuCWKQ6zzgg1DS4vO4GB",
	"3zNhIA4Gb70Mq5nPy/F6/A4ih6uuRMB1VZbge4fKgVFc+q11gqciEe555p5PHuhMxTboBIdqzqWIR5mx",
	"NORIu8f43eqrBzpe0qc0c6f4gDuhVTHlMHOz4u8RT1004/l7QSc41lIeaTeMnJhDZUYupXb4OYYk1Q5U",
	"tBxpNZEiwqenYKzQqnxy3lBPJ3ieohAvwGbStdksU/Q4BhsZQWODQXCqHTD6jk20YW4mLNP0ZY89V3LJ",
	"UgMWlGOLGSgmYQ6SCcseZ1KijUprboWlREI5mIJBkfxMh3Hd8GH+r9vyf8W/oBNMtEm4CwZBlpHmGhtO",
	"wUSgXO5Y9X0dl98xPWFz7cCub5B9F3a3wvD7Kze6msfW9ru73bZfw9X7piwvuHqPUtTW3uqOuYW4w9BA",
	"zM64AYavXy0OTiXUtC7LVlOUtWAp7dAWJuiRTX+pbaFqPfIYr0pgz7R17JTLjI8lsGPJl2D8VoE94hZD",
	"jT0WikuMq4RfPAU1dTN0lzBssSio+EQkazixHW7f64b3u+H9kzAc0P96YRi+qbpIzB10Hb7aMuvU6Cxt",
	"bioPGC6ZH8DcjLvcPpaNQWo1ZU53GPSmPeaAJ7bHnudfo7kUWEQuoayIAbcsjJ8KrSMcJPY6kETVP8E3",
	"UMxcbm4MX+JncTthY4DH6FHBwJkMWtSj+LrG65Zjz06P69bb3tvrBIlQxeedlllzPW7Seq7tWKu7bqVr",
	"xr0CP0Z/fr42BabZWIrIA6J9iiF07XzNNyiS6POpsGIspHDL66Z50XjhshNYx427wrv3T7YOPsW7reMu",
	"u5GmXvqRl51g7tNJTZKtja5SATgEUkxCYnrdgqerketoRG5ZiJD7X1U/Kxxo0325401Y5gOqJQFKz2VW",
	"ur+zH463AYMm5Q49PhgE/3Pnbdg94N3JsPv4/MO9y/+06dyHZt2vh9aKqYKYjZcEfxbMHIzHb50I5yDu",
	"sUMVySwGphXLUjSrRa8nrDdzwhAfAHctEzEoJ9yyBvW3ljtFwqfwysi6QmbOpXbQ73NrwdmeiDjvLbSR",
	"cX93G/b39/lud3t/b7+7Ox5PuuOY8+7+wU64w/kkOhjzXqqmdaDYa0X5JuCcAE/YA20dOUQ9T9SQZutj",
	"kOZkBiWcE9qscIZS8a1BzZp/5w5dyLXJT5+XybXuqJ/TubxMFe9iXMVMOOsp0l/D1w6iKD6IwvvdeCca",
	"d3f59l6X79y/1723vxcdRNsHB9G9rd679BN9bcQTMFqxETfxAqT8eIez2dgJJ1tY56MLZzgTaqIZH+vM",
	"VXSe0wjOUiJJdy1TWTIGU9P4na39FnGuLoRoh5t8LM9ETSeTn54OUy3l56L0ZiXvjaKyVvO0UACnHZeY",
	"itrgAb9jPKHiR0/YmEowyyJu3ccVP23FwJqVcqV1csWvdrrJci/LtF6XeqSTNEPa6bMgCs4Zzs6onsDg",
	"R6ejMlo55oqE6qvfV2mkE0EwXVagI6ktUGlQqc2LL69lj8etJGtdZuWMlpYtEIW9HvWE5SpgMTguJFNa",
	"dXmcCMUyCwbtoJgFGJypLql8UNROVK5aQi6yb17eISWfI0+QwL6jiSzjcsGXFqchyP8e56qUdAO2qiEt",
	"/l0ssRBuhvFr+KJYDiue1Wo4UVGMDZg2MRiIqYATato2E1fLPOLp3SOtYMCULpVQSO70uiLOVMWAqIig",
	"UylvsbAqBKGzCgV1U+ZvNAz3oo3VbrSbJnPMBSxyd7trS9HREBghZKmnYg4D3K1WsHqnHOoVgV6Jg4cT",
	"B4b874pXcAz5dL4soN1FAh1WGHltUnyKPjtgGoM4H7U+cU2tT723r+TBD8U8a6FRHdPQKmJNfpbTwNyi",
	"Cm+J6sOHtiibS8aiydOw1K5izdubYe15hdZci7oJvzj0g4v0V3xcQ9ROkCnxewb51wgJm44a2pHttFY/",
	"1HVAJ3EWAWymFyxBkxa64MwKNZWQY3QODRIi12MPYcLJUZxm6ED+OYYehSsCdd0MCb94WYzJTUEz0Hbr",
	"Ij3jF5UEUeOSKMK4WI1OAdalXDuiSYQSCXrbVlthVRPqGExZxHyyQIhBxHBbROuxI80k6puJCcuUBdf7",
	"CHEvr7Is+lorr73C/RtMfQEGmIEIgTVeHdw1Ffs5wqFxjvDZCM8mknBVECEBhSgzwi1fIgvKi4aI8wfA",
	"DZhhhsTxQzCmT48LAX765SRYd+/D0XDIeBSBxeh5DwpdBd/XRvxBVmQz4DGRVGJcKIefd7UX5PHE8iPO",
	"R1q/F1BIcN1iEY3GAgy/Lz95yk7jfxuORo9evvzt5PnPj45WS/JU/AxYd+GyaqJb6iXFhseH5DiRAe4o",
	"KWspfbKaa3rgqVLSYTaLZozTQVflqDjhLpr5miin+34Pp/7t4fFh5RhjEGz1wl7o61FQPBXBINihR3S6",
	"MCMr9f3K/flWn6TBZ1NoOZZ/Ac4ImCOrYVJYinYupd9Dh1ltnC8G6dSEUh/DGUDFnt1h4PHi8D14As5L",
	"fbp1TOuiTIYn4MDYYPC2kfip9YGLLmYYiU7nC02MTgqD/Z6BWa7sFRXtEs/N6+Hy6/ZB9mbnp1n84zN7",
	"+KOcxy8fJOOd0+zN6EHIn7yavvnl8R/xk9Pl4ZNT9Wbxww9toXI1FnrrOs0m4KLZBhkJ8moirrA/XOtm",
	"JPzCA+BeeA0anhObT7WyPha3w9AfOCkHvufC01SKiOzRf2c9OK5kWDun8nq8ZfV1gpg7fuO6inoCLVA4",
	"4/YILtzxejOvVhyMtZbAVQPeSIL6HC3wdrmOUsMyAsjGPZRj9yNVfG2nsm3hBzxmKD9YR4vufYlFX6n3",
	"Si9UccJDbdFeDfWDwdvzTmCzJOFm6YN7hQ0+X9kWSCE6i+Q51QILQ+2RERhnChb0do8hDy16O/ikk/dG",
	"OoSbutL84K0nUr0G9Bxr28CeXKnURb0thXqPbeoTn+Nmx5DvNw6qXkkU9k/G76eIhYwnl8er/l+vfvuh",
	"wSHeBlS8BeeI/usUZ/VlLRxG615Ny6xn3v4HEV/6IJHgWo7yHtLz4mylOCUtitLxkom44ev+nZq3E527",
	"MtcePiwqPxI2T1xIGVZ5SzSdtj3P3hItbWa03XbSTspZcMu8GmPvxbuf36EorJV2bKIzFX+TjlzzQOpj",
	"tzFFRH8se/0RYKtbrrO/b8Un/wzLSvNLDzfA7maNdiPaUoTHVwP2f+OwSZNKi6RY3DWj6RX1zcoTdQyn",
	"Hnvir4dUGdB7gDS/8YGUiUdGW1t23ahd4GawJKYkfFuOjogwpHIbMaup1ZBXnNbxJePOGTHOqJt3BIuc",
	"fPWLVYuzZFqyysHwwXU8DDf8rcDAV6GP3rq3Tx+/BjDle/lnAtRuePCF1kVmlOhYTIQvlLjSbgam0EKH",
	"GXBmSXFNYSYRPhzLD5W+SVZTQ9jN1Lxf6QRv4j2WdEZNkoKXY+1aUHbffc+bi77pGCPSJaJStuY9JQvO",
	"0b3KM3Wmhv6QMoYUVGyLjupa02te9s3+bm2vM3W01mm1AFVRG2qzKUSlD1dEal6wu2mz9tP7sFc3Xr/b",
	"6rDtDtv5///9v+9vpfV6poa1TrKBCMQcaI/FBD1qJV7HuYurGP9A6n1dLitUsyFZFXaq6oVgfOfzI+OL",
	"IiwMUBbhcy4kXXYum1KV45t/C99GimjPDfj0skHPXd3Y1+aIeXGxp/3Ec8QtWq5oGusJFcrasESbVb9R",
	"q3yhHjtZQdvc/y5CTcTUN0pt2ZU+U8WrCV+u94A9xiHalf1Xyimn5RUVD85RBCm1cMAtAGoZxndacIoC",
	"8n1aQukqvw7p/gzLvD3HUqMdRLjZKRfKOpyfbvhxyWKdobsSeiJEToxOWCQFKEf0Q4AdnCnO3sOSNkTy",
	"Adp4nL9Ft4oi6LEXkFmcwg8m1sJZLCYToLtGuZ4FouQ70kgbMjYOhA9jf0HrbwiMjZ7USOosnki0s8uM",
	"sk5IYKPh8cnox2EhctlSLRpnk245tlvg7A338fr169e9h6+ePfu1Rz3SHj64maDkAFNQaBuImb/YQYZd",
	"a7d3MBdi9mYxxJkHFshdpyT0dtPu1jz2mygWK5d8WsucEm5ar/J8ueZD407GhgRLwmGtUty46LGhtEiQ",
	"0DHB3+5aAWlZrlieNCEJ5+HSAI+Xq/m+Ro3ZYcL/to5F/kd4HcT+4ll+EeaLEYnytFxYSt/5BU3KBU7M",
	"4duviNvyV9VZCGU2JJW/8sEi/SCuZBF+zk/jRDgtLduW/46NjjN/sc0PCjpBZmT1Jn0qqtfogybqP9UR",
	"MgKYt00x6Pclfj/T1g12wjDsB5fnl/8NAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
